export const templateInputFields = {
  1: [
    { label: 'Name', name: 'name', type: 'text' },
    { label: 'Job Title', name: 'jobTitle', type: 'text' },
    { label: 'Principal', name: 'principal', type: 'text' },
    { label: 'School', name: 'school', type: 'text' },
    { label: 'Address', name: 'address', type: 'text' },
    { label: 'Phone', name: 'phone', type: 'text' },
    { label: 'Email', name: 'email', type: 'email' },
    { label: 'LinkedIn', name: 'linkedin', type: 'text' },
    { label: 'Date', name: 'date', type: 'date' },
    { label: 'Letter Content', name: 'letterContent', type: 'textarea' },
  ],
  2: [
    { label: 'Name', name: 'name', type: 'text' },
    { label: 'Job Title', name: 'jobTitle', type: 'text' },
    { label: 'Address', name: 'address', type: 'text' },
    { label: 'Phone', name: 'phone', type: 'text' },
    { label: 'Email', name: 'email', type: 'email' },
    { label: 'LinkedIn', name: 'linkedin', type: 'text' },
    { label: 'Date', name: 'date', type: 'date' },
    { label: 'Letter Content', name: 'letterContent', type: 'textarea' },
  ],
  3: [
    { label: 'First Name', name: 'firstName', type: 'text' },
    { label: 'Last Name', name: 'lastName', type: 'text' },
    { label: 'Job Title', name: 'jobTitle', type: 'text' },
    { label: 'Summary', name: 'summary', type: 'textarea' },
    { label: 'Address', name: 'address', type: 'text' },
    { label: 'Phone', name: 'phone', type: 'text' },
    { label: 'Email', name: 'email', type: 'email' },
    { label: 'LinkedIn', name: 'linkedin', type: 'text' }, 
  ],
};
