# Generated by Django 4.2.13 on 2024-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailrecord",
            old_name="sent_at",
            new_name="created_at",
        ),
    ]
